version: '2'
services:
  chara:
    build: .
    ports:
     - 8080:8080
    volumes:
     - .:/chara
    networks:
      - chara_network
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.0
    environment:
       cluster.name: "docker-cluster"
       xpack.security.enabled: "false"
       xpack.monitoring.enabled: "false"
       xpack.graph.enabled: "false"
       xpack.watcher.enabled: "false"
       ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    mem_limit: 1g
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - chara_network
  kibana:
    image: docker.elastic.co/kibana/kibana:5.3.0
    ports:
      - 5601:5601
    networks:
      - chara_network
    depends_on:
      - elasticsearch


networks:
  chara_network:
    driver: bridge

volumes:
  esdata:
    driver: local